### ISSUE TITLE
학습 데이터 구조 및 필요 데이터 정리

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#10]
## Description

데이터 수집은 가장 오래 걸리는 작업이기 때문에, 먼저 학습에 필요한 데이터들의 구조를 정하고자 합니다.

필요한 데이터들과 학습 시키기 위한 데이터 구조(json 형식)을 정합니다.

## Tasks

- [x] 작은 모델로 학습 테스트
- [x] 데이터 구조 정립
- [x] 데이터 수집 방안 결정

**Comment by jagaldol** [comment]
현재 feature/make-dataset에서 데이터 제작 작업중
