### ISSUE TITLE
(next.js) 서버와의 웹소켓 통신

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#100]
## Description

대화 전송 버튼 눌렀을 때 웹 소켓 통신 연결되도록 설정합니다.

일단 비회원부터 완벽하게 처리하고 회원 기능을 하려고 합니다.
비회원의 첫화면 UI는 완성되었고 대화만 잘 되도록 하면 됩니다. 예외처리 등은 일단 통신되고 결과를 받고 나야 할 수 있을 거 같아 바로 웹소켓 작업을 하겠습니다.

## Tasks

- [x] socket.io로 웹소켓 통신 연결
- [x] 스트리밍으로 오는 메시지 state로 관리하며 실시간으로 처리
- [x] 메시지 보내고 전달 받기 전까지 다음 메시지 전송 불가로 이벤트 막기
- [x] 요청 url 로그인 여부에 따라 변경처리
- [x] 채팅방 선택 안했을 시(chatroomId === 0) 채팅방 생성 및 채팅방으로 메시지 전송
- [x] 채팅 렌더링 구조 비회원과 분리

## References

- [react 로 socket io 연결](https://velog.io/@jungjh123456/react-%EB%A1%9C-socket-io-%EC%97%B0%EA%B2%B0)

**Comment by jagaldol** [comment]
이제 회원용 채팅 작업하겠습니다.

**Comment by jagaldol** [comment]
socket io는 서버도 socket io를 사용해야해서 바닐라 WebSocket API 사용했습니다
