### ISSUE TITLE
(next.js) 채팅 목록 가져오기 무한 스크롤

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#110]
## Description

회원의 채팅을 무한스크롤 형식으로 가져옵니다.

무한스크롤 테스트를 위해 서버에 더미 채팅 내역을 먼저 무수히 많이 만들어야합니다.

더미 채팅 내역을 가지고 무한 스크롤이 제대로 작동하는지 테스트를 하며 정상적으로 랜더링을 시켜야합니다.

## Tasks

- [x] 채팅 더미데이터 추가
- [x] 커서 저장 state 생성
- [ ] 무한 스크롤 구현

**Comment by jagaldol** [comment]
스크롤 위치 조정 문제로 인해 해결불가합니다.
