### ISSUE TITLE
(next.js) 회원 정보 확인하기 창

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#114]
## Description

개인 정보 확인 창에서 개인정보를 확인할 수 있도록 하고 UI 디자인을 해야합니다.

## Tasks

- [x] UI 디자인
- [x] 개인정보 화면에 뿌리기
- [x] 선호하는 음식 목록도 뿌리기
- [x] 버튼(개인정보 변경, 선호도 재설정) 추가
