### ISSUE TITLE
배포 테스트 (웹 서버 및 백엔드 서버)

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#116]
## Description

aws로 프론트 및 백엔드 서버를 배포하고 테스트해봅니다.

> 챗봇의 경우는 여전히 코랩으로 테스트 계속 진행합니다.

## Tasks

- [x] mysql 연결 및 테스트
- [x] 스프링부트 product 프로필 테스트
- [x] 도메인 구매 및 연결
- [x] https 연결
