### ISSUE TITLE
(next.js) 로그인 유효성 검사

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#138]
## Description

![image](https://github.com/jagaldol/chat-foodie/assets/84557643/de777066-d6d2-4bc1-b4ae-7fee4b47152c)

프론트에서의 유효성 검사가 존재 하지 않아 서버의 에러 메시지가 그대로 노출됩니다.

기초적인 유효성 검사를 추가하여 주시길 바랍니다.

## Tasks

- [x] loginId 유효성 검사 및 에러메시지 alert
- [x] password 유효성 검사 및 에러메시지 alert
- [x] 유효성 검사 통과 후 서버로 login 요청 보내도록 수정

## References

joinModal의 유효성 검사 코드를 참고해주세요. 단순히 정규식만 활용하면 될 겁니다.
