### ISSUE TITLE
비회원의 채팅 내역도 쿠키기반으로 잠시 저장 가능하도록 db 수정 필요

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#16]
## Description

비회원도 채팅을 할 수 있게 하기 위해 db 수정

## Tasks

- [ ] 비회원일 시 서버가 해당 client 식별할 쿠키 필요
- [ ] 비회원의 경우 채팅방 하나만 가능
- [ ] 비회원 쿠키를 기반으로 메시지를 저장하도록 db 구조 변경 필요

**Comment by jagaldol** [comment]
비회원의 경우 대화내역을 수집하기는 하지만 저장은 온전히 클라이언트의 책임으로 전환
