### ISSUE TITLE
self-instruct 코드 작성

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#22]
## Description

오픈소스의 코드는 davinci 모델을 사용하고 있기에, 비용 절감을 위해 gpt 3.5-turbo를 사용하는 코드로 새롭게 제작할 필요가 있습니다. 또한, 한국어를 생성할 수 있게 prompt도 한국어로 번역할 필요가 있어 간략화하여 새롭게 스크립트를 만들 예정입니다.

## Tasks

- [x] gpt 3.5 turbo 사용하는 ChatCompletion api로 구현
- [x] instruction generation 코드 작성
- [x] response generation 코드 작성

## References

- [chat completions api](https://platform.openai.com/docs/guides/gpt/chat-completions-api)
- [self instruct](https://github.com/yizhongw/self-instruct)
- [ko alpaca](https://github.com/Beomi/KoAlpaca)
