### ISSUE TITLE
챗봇 서버 구동 스크립트 작성

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#23]
## Description

현재까지의 토의로 `oobabooga/text-generation-webui`의 오픈소스를 사용하여 챗봇 AI rest api 서버를 구성하기로 하였음

## Tasks

- [x] 원본 repo를 fork하여 작업
- [x] character 폴더의 instruction-followiing 우리가 만들 모델에 맞게 제작
- [x] Example.yaml의 형식으로 챗봇 기본 캐릭터 작성
- [x] GPU대신 CPU를 사용하는 거나 기타 4, 8bit 등의 하드웨어 성능을 최소화하여 구동 시킬 수 있는 방안 탐색
- [x] 원본 repo(text-generation-webui)의 라이센스를 분석하여 어디까지 수정이 가능한지 파악 필요
  - [x] 가능하다면 소스코드에 살짝의 수정을 하여 불필요한 WEBUI 구동파트를 제거
- [x] fork한 우리의 저장소를 clone부터 폴더 내부에 모델 업로드 후 api 서버까지 구동시키는 쉘 스크립트 작성

## References

- [oobabooga/text-generation-webui](https://github.com/oobabooga/text-generation-webui)
  - [api 핵심 코드](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/api)
  - [api 사용 예시 파이썬 스크립트](https://github.com/oobabooga/text-generation-webui/tree/main/api-examples)

**Comment by jagaldol** [comment]
쉘 스크립트는 따로 작성하지 않았고 그냥 colab demo 만들었습니다.
