### ISSUE TITLE
(spring boot) 회원가입 로직 개선

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#29]
## Description

현재 이메일 중복 체크를 안하고 있습니다.

이메일 중복 체크 뿐만 아니라 회원가입 요청 시 request의 validation을 검증할 필요 가 있습니다. spring-validation을 사용해서 requestDTO를 검증하고 예외 처리를 마쳐야합니다.

이메일 인증(메일 전송) 및 OAuth2(구글 로그인, 카카오톡 로그인)는 별개의 issue로 추가적으로 작업 예정입니다.

## Tasks

- [x] requestDTO 작성
- [x] requestDTO validation 체크 및 exception 처리
- [x] response 잘되는지 확인
- [x] 서비스에서 이메일 등 중복되면 안되는 unique key의 경우 exeception 던지기

**Comment by jagaldol** [comment]
로그인 아이디도 중복 되면 안되네요 생각해보니까 이메일 인증하기 버튼 누르면 중복 검사 및 데이터 유효성 검사 한 다음에 일단 유저에 가입 시켜주고(테이블에 저장) 그다음에 이메일 인증되면 권한을 주는게 나을 것 같아요

**Comment by jagaldol** [comment]
추가적으로 화면 설계상에는 비밀번호 입력 창만 있는데 비밀번호와 비밀번호 확인 2개가 들어와야 할 것입니다.
