### ISSUE TITLE
데이터베이스의 음식들에 매칭되는 이미지 수집

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#30]
## Description

현재 db에 들어가는 음식 목록들에 대응하는 이미지를 수집해야 합니다.

일정한 비율 - 현재 figma에서 150x100 사이즈 - 로 이미지를 수집 해주시기 바랍니다.

비율이 안맞는 경우 - 세로로 엄청 긴 이미지(예 - 츄러스) 의 경우 리사이즈 되며 이미지가 찌그러지게 됩니다.

크기는 줄이면 되나 비율은 처음부터 맞춰주셔야 합니다.

## Tasks

- [x] 음식 이미지 수집
- [x] 음식 이미지 비율 맞는지 확인
- [x] 음식 이름으로 이미지 파일 이름 통일 및 확장자도 왠만하면 통일
- [x] db 쿼리에 이미지 주소 추가 -> 단순히 {음식이름}.png 라면 쿼리 작성이 간편해짐

**Comment by jagaldol** [comment]
#44 이 PR에서 음식 기본 정보 저장을 하며 음식 사진 url을 jpg로 임시 작성해놨습니다. PR 내용도 확인한번 하고 추후 음식 사진 넣을 때 data.sql에도 확장자 맞춰주시길 바랍니다.
