### ISSUE TITLE
변경된 db 구조를 Entity에 반영

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#32]
## Description

처음에는 schema.sql로 작성해서 바로 mysql로 `CREATE TABLE IF NOT EXISTS` 하여 테이블을 작성하게 했었지만, 개발 단계에서 h2 인메모리 db를 사용하도록 변경하였습니다.

현재 로직은 hibernate가 Entity class들 기반으로 자동으로 table을 생성해줍니다. 따라서 Entity 클래스를 설계에 맞게 변경해야합니다.

그리고 user 테이블의 경우 user가 예약어로 등록되어 있어 user_tb로 테이블 명을 바꿨습니다. 다른 테이블도 _tb를 붙여서 통일해야합니다.

## Tasks

- [x] User.java 수정
- [x] Favor.java 수정
- [x] Food.java 수정
- [x] Chatroom.java 수정
- [x] Message.java 수정

## References

- User.java는 @jagaldol 이 수정해놓을 테니까 이거 참고해서 작성해주세요.

**Comment by jagaldol** [comment]
food 작업 중입니다.
