### ISSUE TITLE
(spring boot) 회원가입 도중의 이메일 인증

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#34]
## Description

이메일 인증을 위해 POST api/email-validation 이 오면, 메일을 보내주고 SMTP(Simple Mail Transfer Protocol) 인증 번호를 서버에 저장합니다.(DB에 추가적인 테이블 필요)

추후 POST /join 요청이 올 때, request body에 같이 인증번호를 담아서 주면 조회해서 일치하면 넣어줍시다.

그리고 이 작업을 할 시점에는 이메일 중복 검사 로직이 회원가입 서비스에 있을 건데 그 부분을 여기로 옮겨줘야 할겁니다.

## Tasks

- [x] 이메일 인증하기 요청 시 이메일 중복 검사
- [x] 이메일 보내주기
- [x] 랜덤하게 만든 숫자를 서버 db에 저장
- [x] 회원가입 요청 때 인증번호 검사 후 통과 시키기

**Comment by jagaldol** [comment]
회원가입 이슈에도 코멘트를 달았는데, 회원가입은 그냥 유효성 검사 및 중복 검사 후 진행 시키고 메일 인증을 하면 권한을 주는 것으로 처리하겠습니다.

이 이슈를 처리할때는 인증 메일 보내기 api와 인증하기 api로 총 2개를 만들어야 합니다. join이 되어 저장되면 자동으로 메일을 보내도록 redirect 처리합니다(혹은, 프론트에서 정상 리턴 되면 그냥 인증 메일 보내기 api 호출을 한번 더 해주게 처리해도 됩니다).

유저 테이블에 권한에 대한 column을 role을 추가해야하고, JWT에 role을 같이 전달해줍니다. 추가적으로 JWT의 권한정보를 바탕으로 접근 제어 해야합니다.
![image](https://github.com/jagaldol/chat-foodie/assets/84557643/94996f37-c69d-4641-902c-1b787a0038f7)

화면 설계 상에는 회원가입 완료하기 버튼 밖에 없는데 나중에 인증메일 재발송 버튼을 추가할 겁니다.

로그인 시 JWT를 바탕으로 권한이 없으면(role 정보) 인증번호 입력 화면만 나오도록 처리할 겁니다. X누르고 빠져 나가면 로그인 실패(JWT 버리기)
