### ISSUE TITLE
(spring boot) 유저 선호도 저장

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#36]
## Description

이전 이슈 #35 에서 음식 목록을 리턴 해줬는데 이 중에서 선택한 음식 선호도 리스트를 서버에 저장해야합니다.

현재 화면 설계로는 음식 선호정도(like_score)를 별도 지정할 수 있는 UI가 존재 하지 않습니다. table에서 like_score를 없애던지 아니면 일단 1로 넣던지 하여 추후 UI 변경 시 requestDTO를 수정하며 로직을 추가하면 될 것입니다.

선호도 저장 요청이 오면 기존에 있던 해당 유저의 선호도를 완전 삭제(비우기) 후 새로 insert 합니다.

## Tasks

- [x] favor table 다듬기
- [x] 원래 저장되어 있던 선호도 삭제
- [x] 요청 받은 선호도로 새로 저장

## References

- 이슈 #35 와 연관이 깊습니다.
- 기존껄 지우고 새로 insert하니까 transaction을 잘 써야합니다.
