### ISSUE TITLE
(spring boot) 개인정보 확인

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#37]
## Description

화면 설계 상에는 개인 정보 확인 및 변경이 없지만 당연히 필요한 기능입니다. 화면 어딘가에 버튼을 만들 예정입니다.

이 이슈에서는 개인 정보 조회만을 다룹니다.

회원 가입 시 작성한 개인 정보 및 개인 선호도를 리턴해줍니다.

## Tasks

- [x] user_tb 조회해서 자기 정보 들고오기
- [x] favor_tb 조회해서 선호도 들고오기
- [x] 개인 정보랑 선호도 정보 잘 버무려서 responseDTO 이쁘어 응답주기
