### ISSUE TITLE
(spring boot) API 문서 작성

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#40]
## Description

필요한 api들을 정리하고 Restful 하도록 주소 설계 및 request의 구조, response의 구조를 작성합니다.

각 api의 제약 사항과 예측 가능한 예외 케이스를 작성하고 예외에 대한 response 예시 또한 작성합니다.

## Tasks

- [x] api 주소 설계
- [x] 각 request 예시 작성
- [x] 각 response 예시 작성
- [ ] 잘못된 요청(request)에 대한 에러 응답 예시 작성

**Comment by jagaldol** [comment]
https://sanghaklee.tistory.com/57

**Comment by jagaldol** [comment]
8.3.(목) 기준, 이 이슈 이전의 이슈들은 api-docs에서 작성 완료됨
