### ISSUE TITLE
채팅 내역을 보관할 테이블 만들기

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#6]
## Description

테이블 구조를 만들어야 합니다.

우리의 채팅 구조는 대답하는 쪽이 항상 서버이므로 메시지에 fromId, toId가 아닌 다른 구조가 필요할 것입니다.

채팅방 테이블과 채팅 테이블을 분리해 정규화를 시도할 수 있을 것입니다.

## Tasks

- [x] 테이블 스키마 생성
- [x] 채팅방 테이블 생성 및 테스트
- [x] 채팅 테이블 생성 및 테스트
