### ISSUE TITLE
(spring boot) /api/public-chat 완성하기

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#66]
## Description

현재 연결 테스트 및 답변 생성은 완료 했지만, 서버는 중간에서 프록시 역할만 할 뿐 값 처리를 전혀 하지 않습니다.

Message를 DTO로 객체 지향적으로 관리하며 클라이언트 쪽에서 필요한 정보만 전달 받고 나머지 파라미터는 서버  내부에서 관리할 예정입니다.

## Tasks

- [x] 챗봇으로 보낼 정보를 DTO로 관리
- [x] 클라이언트에서 보내오는 정보를 DTO로 관리
- [x] API 명세를 보고 클라이언트의 메시지를 후처리하여 챗봇에게 전달
- [x] 챗봇에게서 오는 정보도 DTO로 관리
- [x] 챗봇에게서 온 정보를 후처리하여 클라이언트에게 전달
