### ISSUE TITLE
(spring boot) /api/chat 완성하기

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#68]
## Description

#66 이거 먼저 해결 후 public-chat의 구조와 동일하게 가는데 history 대신 채팅방이 전달이 됩니다. 채팅방의 채팅을 조회하여 history를 서버에서 만듭니다.

챗봇에게 회원이름 기반으로 전달해야합니다.

챗봇에게 전달할때 맨처음 대화 내역으로 좋아하는 음식 리스트를 전달해줘야합니다.

또한 public-chat과는 다르게 요청과 응답을 한번에 저장하는게 아닌 `is_from_chatbot`을 기반으로 구별하여 message_tb에 집어 넣습니다.

사용자의 메시지를 집어넣고, 챗봇의 응답이 완료된 시점에 챗봇의 응답도 메시지 테이블에 집어넣습니다.

## Tasks

- [x] 해당 회원의 채팅방인지 검사
- [x] 선호도를 처리
- [x] 채팅방의 내역 내역 들고와 history 생성
- [x] 요청 메시지 및 챗봇이 생성한 메시지 db에 저장
- [x] 기타 필요한 것들

**Comment by jagaldol** [comment]
챗봇 서버 안켜져있거나 하여 연결 실패 시 클라이언트에게 챗봇에 연결할 수 없다고 에러 메시지 돌려주기
