### ISSUE TITLE
서비스 UI 디자인(화면, 로고 등)

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#7]
## Description

figma로 UI 디자인 하기

https://www.figma.com/file/zZKCsyv8dxf5fr810MWZxX/Untitled?type=design&node-id=0-1&t=ffg7Q5WOw7G1jbCJ-0

메일로 초대 보내 놓았음

## Tasks

- [x] 먼저, chatgpt UI를 들고오기
- [x] 로고 만들기
- [x] 우리 서비스 디자인 만들기
- [x] 메인 화면(채팅 서비스 화면)
- [x] 로그인 창
- [x] 회원가입 창
- [ ] 공지사항
- [ ] 건의 및 문의 글작성

**Comment by jagaldol** [comment]
공지사항 및 건의 문의 글 작성은 우선 순위에서 밀려 이정도로 일단락 내림
