### ISSUE TITLE
(spring boot) /api/chatrooms/{chatroomId}/messages 대화 기록 조회하기

### ISSUE THREAD

**Issue by icarus012832** [jagaldol/chat-foodie#75]
## Description

회원이 채팅방 목록에서 채팅방을 클릭하면 대화 기록을 조회할 수 있게 해줍니다.
각 채팅방 마다 대화 기록을 저장해둬야 하고, 대화가 챗봇의 답변인지 회원이 입력한 내용인지 구분해야 합니다.
또한 채팅을 입력하거나 받은 시간도 저장합니다.

## Tasks

- [x] 각 채팅방에 대화 기록 저장하기.
- [x] 대화가 챗봇의 답변인지 회원이 입력한 내용인지 구분하여 저장하기.
- [x] 채팅 입력, 받은 시간 저장하기
- [x] 채팅방 클릭시 대화 기록을 사용자에게 전달하기.

## References

- #73
