### ISSUE TITLE
프론트 개발 환경 구축

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#8]
## Description

프론트 개발 환경 구축 필요

## Tasks

- [ ] Next.js 빌드
- [ ] 백엔드 api 사용 되는 지 테스트
- [ ] 페이지 별 라우팅 및 SSR 작업
