### ISSUE TITLE
LLM 모델 테스트

### ISSUE THREAD

**Issue by jagaldol** [jagaldol/chat-foodie#9]
## Description

파인 튜닝을 하기 전 LLM을 실행해 보고 모델의 구조와 성능을 확인

## Tasks

- [x] LLM 모델 로컬에서 실행
- [x] 모델에 input과 output의 구조를 확인
- [ ] 서버에서 돌아가는지 테스트
- [x] 학습 데이터의 구조 정하기
