### ISSUE TITLE
(next.js) 회원가입 창 만들기

### ISSUE THREAD

**Issue by sm136599** [jagaldol/chat-foodie#94]
## Description

유저가 회원가입 시 접하는 창을 만듭니다.

## Tasks

- [x] 회원가입 창 UI 만들기
- [x] 유효성 검사 만들기(하나씩 분리해서)
- [x] 이메일 인증 창 UI 만들기
- [x] 이메일 인증 프론트 코드 구현
- [x] #107
