### ISSUE TITLE
(next.js) 선호 음식 고르는 창 만들기

### ISSUE THREAD

**Issue by icarus012832** [jagaldol/chat-foodie#95]
## Description

(next js) 선호 음식 고르는 창 만들기

## Tasks

- [ ] 사진을 30개 받아서 1페이지당 6개씩 5페이지로 만들기
- [ ] 현재 페이지가 어딘지 화면에 뜨게 하기
- [ ] 선택한 음식을 리턴하기
